/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: d1a7b6c80850f3bb5b91d7a2b727bd1e)
interface __BaseEnv_Env {
	R2: R2Bucket;
	AI: Ai;
	R2_PUBLIC_URL: "https://pub-0772ac25cee64e29a26d637700fdd2b7.r2.dev";
	GUARDRAIL_GATEWAY: "block";
	MESSAGE_GATEWAY: "allow";
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_PUBLIC_URL" | "GUARDRAIL_GATEWAY" | "MESSAGE_GATEWAY" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_API_TOKEN">> {}
}
